-- Migración 017: Arreglar RLS - deshabilitar en todas las tablas restantes

ALTER TABLE user_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE story_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE story_replies DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_mutes DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;

-- Refrescar caché de PostgREST
NOTIFY pgrst, 'reload schema';
